<a href="https://colab.research.google.com/github/vishnuk88/texti/blob/main/priceVariation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
from sklearn.feature_extraction.text import TfidfTransformer,CountVectorizer
from nltk.stem import WordNetLemmatizer 
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
import seaborn as sns
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.

True

In [2]:
df = pd.read_csv("/content/drive/MyDrive/runningMate/export_dataframe.csv")
df.head()

            categorys                                    name    price
0  Traditional Weaves  Screen Printed Pin-Tucks Cotton Fabric  ₹299.00
1  Traditional Weaves  Screen Printed Pin-Tucks Cotton Fabric  ₹299.00
2  Traditional Weaves  Screen Printed Pin-Tucks Cotton Fabric  ₹299.00
3  Traditional Weaves  Screen Printed Pin-Tucks Cotton Fabric  ₹299.00
4  Traditional Weaves  Screen Printed Pin-Tucks Cotton Fabric  ₹299.00

In [11]:
df = df.replace('₹','', regex=True).replace(',','',regex=True)
df['price'] =df['price'].astype(str).astype(float)
df.dtypes

categorys     object
name          object
price        float64
dtype: object

In [16]:
 nltk.download('stopwords')
stop = stopwords.words('english')
df['NoStopWordName'] = df['name'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
df['NoStopWordName'] = df['NoStopWordName'].astype(str)
df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

            categorys  ...                          NoStopWordName
0  Traditional Weaves  ...  Screen Printed Pin-Tucks Cotton Fabric
1  Traditional Weaves  ...  Screen Printed Pin-Tucks Cotton Fabric
2  Traditional Weaves  ...  Screen Printed Pin-Tucks Cotton Fabric
3  Traditional Weaves  ...  Screen Printed Pin-Tucks Cotton Fabric
4  Traditional Weaves  ...  Screen Printed Pin-Tucks Cotton Fabric

[5 rows x 4 columns]

In [22]:
df['_any'] = df['name'].str.len() - df['NoStopWordName'].str.len()
df.query('_any > 0')

                categorys  ... _any
1985   Traditional Weaves  ...    1
1986   Traditional Weaves  ...    1
2369   Traditional Weaves  ...    1
2371   Traditional Weaves  ...    1
2372   Traditional Weaves  ...    1
...                   ...  ...  ...
34012       Wraps & Robes  ...    5
34013       Wraps & Robes  ...    5
34014       Wraps & Robes  ...    5
34015       Wraps & Robes  ...    5
34016       Wraps & Robes  ...    5

[479 rows x 5 columns]